"""initial migrate

Revision ID: cd7c3f3aeb52
Revises: 
Create Date: 2026-08-24 21:10:25.701559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd7c3f3aeb52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('fk_related_news_news_idx'), table_name='related_news')
    op.drop_index(op.f('fk_related_news_related_idx'), table_name='related_news')
    op.drop_index(op.f('news_related_unique'), table_name='related_news')
    op.drop_table('related_news')
    op.drop_index(op.f('fk_ai_chat_user_idx'), table_name='ai_chat')
    op.drop_index(op.f('idx_created_at'), table_name='ai_chat')
    op.drop_table('ai_chat')
    op.alter_column('favorite', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='收藏id',
               existing_comment='收藏ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='用户id',
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('favorite', 'news_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='新闻id',
               existing_comment='新闻ID',
               existing_nullable=False)
    op.alter_column('favorite', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment='创建时间',
               existing_comment='收藏时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('fk_favorite_news_idx'), table_name='favorite')
    op.drop_index(op.f('fk_favorite_user_idx'), table_name='favorite')
    op.create_index('fx_favorite_news_idx', 'favorite', ['news_id'], unique=False)
    op.create_index('fx_favorite_user_idx', 'favorite', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_favorite_user'), 'favorite', type_='foreignkey')
    op.drop_constraint(op.f('fk_favorite_news'), 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'news', ['news_id'], ['id'])
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['id'])
    op.drop_table_comment(
        'favorite',
        existing_comment='收藏表',
        schema=None
    )
    op.alter_column('history', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='浏览历史id',
               existing_comment='历史ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('history', 'news_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='新闻id',
               existing_comment='新闻ID',
               existing_nullable=False)
    op.alter_column('history', 'user_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True,
               comment='用户id',
               existing_comment='用户ID')
    op.alter_column('history', 'view_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment='新闻查看时间',
               existing_comment='浏览时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('fk_history_news_idx'), table_name='history')
    op.drop_index(op.f('fk_history_user_idx'), table_name='history')
    op.drop_index(op.f('idx_view_time'), table_name='history')
    op.create_index('hx_news_idx', 'history', ['news_id'], unique=False)
    op.create_index('hx_user_idx', 'history', ['user_id'], unique=False)
    op.create_unique_constraint('unique_user_news', 'history', ['user_id', 'news_id'])
    op.drop_constraint(op.f('fk_history_news'), 'history', type_='foreignkey')
    op.drop_constraint(op.f('fk_history_user'), 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'news', ['news_id'], ['id'])
    op.create_foreign_key(None, 'history', 'user', ['user_id'], ['id'])
    op.drop_table_comment(
        'history',
        existing_comment='浏览历史表',
        schema=None
    )
    op.alter_column('news', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='新闻id',
               existing_comment='新闻ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('news', 'content',
               existing_type=mysql.TEXT(),
               comment='内容',
               existing_comment='新闻内容',
               existing_nullable=False)
    op.alter_column('news', 'category_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='分类id',
               existing_comment='分类ID',
               existing_nullable=False)
    op.alter_column('news', 'publish_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='发布时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('fk_news_category'), 'news', type_='foreignkey')
    op.drop_table_comment(
        'news',
        existing_comment='新闻表',
        schema=None
    )
    op.alter_column('news_category', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment=None,
               existing_comment='分类ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('news_category', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_comment='分类描述')
    op.alter_column('news_category', 'sort_order',
               existing_type=mysql.INTEGER(),
               comment='排序',
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('news_category', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news_category', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('name_UNIQUE'), table_name='news_category')
    op.drop_table_comment(
        'news_category',
        existing_comment='新闻分类表',
        schema=None
    )
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='用户id',
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户账号',
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='加密存储密码',
               existing_comment='密码（加密存储）',
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=11),
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('phone_UNIQUE'), table_name='user')
    op.create_index('phone_UNIQUE', 'user', ['phone'], unique=False)
    op.drop_index(op.f('username_UNIQUE'), table_name='user')
    op.create_index('username_UNIQUE', 'user', ['username'], unique=False)
    op.drop_table_comment(
        'user',
        existing_comment='用户信息表',
        schema=None
    )
    op.alter_column('user_token', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='令牌id',
               existing_comment='令牌ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_token', 'user_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True,
               comment='用户id',
               existing_comment='用户ID')
    op.alter_column('user_token', 'expires_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='过期时间',
               existing_nullable=False)
    op.alter_column('user_token', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('token_UNIQUE'), table_name='user_token')
    op.create_index('token_UNIQUE', 'user_token', ['token'], unique=False)
    op.drop_constraint(op.f('fk_user_token_user'), 'user_token', type_='foreignkey')
    op.create_foreign_key(None, 'user_token', 'user', ['user_id'], ['id'])
    op.drop_table_comment(
        'user_token',
        existing_comment='用户令牌表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_token',
        '用户令牌表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'user_token', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_token_user'), 'user_token', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('token_UNIQUE', table_name='user_token')
    op.create_index(op.f('token_UNIQUE'), 'user_token', ['token'], unique=True)
    op.alter_column('user_token', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_token', 'expires_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='过期时间',
               existing_nullable=False)
    op.alter_column('user_token', 'user_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False,
               comment='用户ID',
               existing_comment='用户id')
    op.alter_column('user_token', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='令牌ID',
               existing_comment='令牌id',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'user',
        '用户信息表',
        existing_comment=None,
        schema=None
    )
    op.drop_index('username_UNIQUE', table_name='user')
    op.create_index(op.f('username_UNIQUE'), 'user', ['username'], unique=True)
    op.drop_index('phone_UNIQUE', table_name='user')
    op.create_index(op.f('phone_UNIQUE'), 'user', ['phone'], unique=True)
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'phone',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(length=20),
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码（加密存储）',
               existing_comment='加密存储密码',
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名',
               existing_comment='用户账号',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='用户ID',
               existing_comment='用户id',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'news_category',
        '新闻分类表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('name_UNIQUE'), 'news_category', ['name'], unique=True)
    op.alter_column('news_category', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('news_category', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news_category', 'sort_order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_comment='排序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('news_category', 'description',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               nullable=True,
               existing_comment='分类描述')
    op.alter_column('news_category', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='分类ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'news',
        '新闻表',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_news_category'), 'news', 'news_category', ['category_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('news', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('news', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news', 'publish_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='发布时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('news', 'category_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='分类ID',
               existing_comment='分类id',
               existing_nullable=False)
    op.alter_column('news', 'content',
               existing_type=mysql.TEXT(),
               comment='新闻内容',
               existing_comment='内容',
               existing_nullable=False)
    op.alter_column('news', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='新闻ID',
               existing_comment='新闻id',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'history',
        '浏览历史表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_history_user'), 'history', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_history_news'), 'history', 'news', ['news_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('unique_user_news', 'history', type_='unique')
    op.drop_index('hx_user_idx', table_name='history')
    op.drop_index('hx_news_idx', table_name='history')
    op.create_index(op.f('idx_view_time'), 'history', ['view_time'], unique=False)
    op.create_index(op.f('fk_history_user_idx'), 'history', ['user_id'], unique=False)
    op.create_index(op.f('fk_history_news_idx'), 'history', ['news_id'], unique=False)
    op.alter_column('history', 'view_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='浏览时间',
               existing_comment='新闻查看时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('history', 'user_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False,
               comment='用户ID',
               existing_comment='用户id')
    op.alter_column('history', 'news_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='新闻ID',
               existing_comment='新闻id',
               existing_nullable=False)
    op.alter_column('history', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='历史ID',
               existing_comment='浏览历史id',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'favorite',
        '收藏表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key(op.f('fk_favorite_news'), 'favorite', 'news', ['news_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_favorite_user'), 'favorite', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('fx_favorite_user_idx', table_name='favorite')
    op.drop_index('fx_favorite_news_idx', table_name='favorite')
    op.create_index(op.f('fk_favorite_user_idx'), 'favorite', ['user_id'], unique=False)
    op.create_index(op.f('fk_favorite_news_idx'), 'favorite', ['news_id'], unique=False)
    op.alter_column('favorite', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='收藏时间',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('favorite', 'news_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='新闻ID',
               existing_comment='新闻id',
               existing_nullable=False)
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='用户ID',
               existing_comment='用户id',
               existing_nullable=False)
    op.alter_column('favorite', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='收藏ID',
               existing_comment='收藏id',
               existing_nullable=False,
               autoincrement=True)
    op.create_table('ai_chat',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='聊天记录ID'),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('message', mysql.TEXT(), nullable=False, comment='用户消息'),
    sa.Column('response', mysql.TEXT(), nullable=False, comment='AI回复'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ai_chat_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI聊天记录表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='AI聊天记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_created_at'), 'ai_chat', ['created_at'], unique=False)
    op.create_index(op.f('fk_ai_chat_user_idx'), 'ai_chat', ['user_id'], unique=False)
    op.create_table('related_news',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='关联ID'),
    sa.Column('news_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='新闻ID'),
    sa.Column('related_news_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='相关新闻ID'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_related_news_news'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_news_id'], ['news.id'], name=op.f('fk_related_news_related'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='相关新闻关联表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='相关新闻关联表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('news_related_unique'), 'related_news', ['news_id', 'related_news_id'], unique=True)
    op.create_index(op.f('fk_related_news_related_idx'), 'related_news', ['related_news_id'], unique=False)
    op.create_index(op.f('fk_related_news_news_idx'), 'related_news', ['news_id'], unique=False)
    # ### end Alembic commands ###
